### ISSUE TITLE
Determine if @Mocked is needed for Twilio object in tests

### ISSUE THREAD

**Issue by SimonOsnes** [DD2480-Group-8/twilio-java#23]
When mocking an object, it will return the correct answer if nothing else i stated. This may make some test fail. .

**Comment by emilmyresten** [comment]
Now that i've read a bit about it, I don't think Twilio should have the @Mocked tag, since it is not "a dependency that can be mocked away", rather, it is quite central to the tests we need to perform.

"[...] particular tests may not be interested in exercising all components, layers, or sub-systems involved [in a class]. Such parts of the system may then be "mocked away" (or faked), so that the code under test runs in isolation from them. Therefore, the ability to isolate the code under test from certain parts of the system is generally useful in all kinds of tests. That said, in general it's best to make a test as "realistic" as we can. So, the use of mocking and/or faking should, ideally, be kept to a minimum." 

https://jmockit.github.io/tutorial/Introduction.html#isolation
